### ISSUE TITLE
Feature: separate :entities for columns and tables

### ISSUE THREAD

**Issue by aceful** [seancorfield/next-jdbc#10]
In `clojure.java.jdbc` I've sometimes wished I could specify different `:entities` fns for column names versus table names. What do you think about keeping `:entities` as-is and adding `:entities.tables` and `:entities.columns` (or something along those lines)?

**Comment by seancorfield** [comment]
I'm trying to streamline the API rather than make it more complex. I'm still trying to decide whether those "sugar" functions (the ones that use `:entities`) should even stay in the core API, at this point.

**Comment by seancorfield** [comment]
I revisited this in the latest round of API updates and there are now `:table-fn` and `:column-fn` options **instead of** the single `:entities` function. I removed `:identifiers` too (result set builders are pluggable enough to allow you to provide any custom column naming strategy you need).
