### ISSUE TITLE
Allow map(s) as parameter to insert! and insert-multi!

### ISSUE THREAD

**Issue by hoxu** [seancorfield/next-jdbc#105]
**Is your feature request related to a problem? Please describe.**

clojure.java.jdbc `insert!` and `insert-multi!` allow passing map(s):

https://clojure.github.io/java.jdbc/#clojure.java.jdbc/insert!

> Usage: (insert! db table row)

https://clojure.github.io/java.jdbc/#clojure.java.jdbc/insert-multi!

> Usage: (insert-multi! db table rows)

**Describe the solution you'd like**

next.jdbc could allow a map and a sequence of maps as parameters to `insert!` and `insert-multi!` respectively.

**Comment by seancorfield** [comment]
`clojure.java.jdbc/insert-multi!` does multiple inserts if you pass a sequence of maps -- it's exactly the same as:
```clojure
(doseq [row sequence-of-maps]
  (jdbc/insert! db table row))
```
`next.jdbc` deliberately avoids this unoptimized form and forces you to "do the right thing". This is by design. As the documentation says:
> They are deliberately simple and intended to cover only the most common, basic SQL operations. The primary API (plan, execute!, execute-one!) is the recommended approach for everything beyond that.

**Comment by hoxu** [comment]
@seancorfield: How about providing a compatible API **and** doing the right thing? Something like:

```clojure
(let [cols (keys (first rows))]
    (insert-multi! *db* :table cols (map (apply juxt cols) rows)))
```

This makes the assumption that keys are the same in all maps/rows, but I think that's reasonable.

**Comment by seancorfield** [comment]
The `next.jdbc.sql` namespace is not going to be expanded. The primary API is `next.jdbc`. Also, as the docs explain, even the "right thing" can require database-specific options to have the operation be a single multi-row insert.
