### ISSUE TITLE
How to execute SQL DDL script?

### ISSUE THREAD

**Issue by johanhaleby** [seancorfield/next-jdbc#111]
Is it possible to execute a SQL script using next-jdbc? I.e. let's say I have a `sql` file on classpath or disk and I just want to run this file and insert it to the DB. Is this possible? Sorry if this is documented somewhere but I cannot seem to find it.

**Comment by seancorfield** [comment]
You would need to read it into a string (e.g., via `slurp`) and then use it as a regular SQL string in a call to `execute-one!`, assuming it is a single SQL command.

If it is multiple SQL statements, separated by `;`, you may need to break it into multiple SQL commands (and call `execute-one!` on each) or you may be able to execute the whole thing (again via `execute-one!`), depending on what your database and/or JDBC driver allows.

If you want to keep your SQL code in files separate from your code, as a general rule, then you should look at [HugSQL](https://www.hugsql.org/) which supports `next.jdbc` and is both well-documented and well-maintained.
