### ISSUE TITLE
Storing values of the clojure.lang.Keyword type

### ISSUE THREAD

**Issue by darkleaf** [seancorfield/next-jdbc#114]
How can I store and fetch a keyword in Postgres? 

Domain types are not working. JDBC treats them as strings.
Composite types are too complex.

**Comment by seancorfield** [comment]
You'd have to translate keywords to something that PostgreSQL can store (and translate them back on fetch). GitHub issues are not a good way to have a discussion about something open-ended like this (I do not use PostgreSQL so I know very little about its custom types). I'd recommend you join the `#sql` channel on the Clojurians Slack and ask how other PostgreSQL users handle this.

Sign up for Slack here: http://clojurians.net -- Messages etc here: https://clojurians.slack.com
