### ISSUE TITLE
Is direct support for CallableStatement worthwhile?

### ISSUE THREAD

**Issue by seancorfield** [seancorfield/next-jdbc#120]
This is related to #116 and is for discussion around whether it is worth `next.jdbc` supporting `CallableStatement` directly, to make it easier to use stored procedures.

Currently, the work in #116 is generic and will support multiple result sets (and update counts) coming back from `.execute()` and therefore work with any SQL that potentially returns multiple result sets. You have to opt-in to the machinery that looks for multiple result sets (and you get back a sequence of result sets instead of just a single result set).

`CallableStatement` extends `PreparedStatement` and adds `get`/`set`/`registerOut` methods for interacting with the parameters. The docs seem to indicate that `CallableStatement` is (only) needed to support the portable, shorthand notation for calls, namely `{call the_proc(arg1,arg2)}` and `{?= call the_proc(arg1,arg2)}` and that all OUT parameters must be registered before the call (I'm not clear whether that applies when calling SPs via the regular `EXEC` syntax in a `PreparedStatement`?).

The docs note that you should only `get` the OUT parameter values after all the result sets have been retrieved "for maximum portability".

https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/CallableStatement.html

**Comment by seancorfield** [comment]
Closing due to lack of requests for this functionality.

**Comment by blindcoding9** [comment]
Hey Sean!
I would like to record an example of usage here; it took me some time to figure out how to consume OUT parameters from a PL/SQL call.

```clojure
(with-open [conn (next.jdbc/get-connection {:jdbcUrl  "jdbc:oracle:thin:@...",
                                         :user     "user",
                                         :password "p"}) ]
    (let [sql "
              declare
                 l_message_handle raw(16);
                 l_message_string varchar2(100);
                 l_message_number number;
              begin
                 l_message_handle := utl_raw.cast_to_raw('123456789ABCDEF0');
                 l_message_string := 'Mensagem gerada';
                 l_message_number := 42;

                 :output_msg_id := l_message_handle;
                 :output_msg_string := l_message_string;
                 :output_msg_number := l_message_number;
              end;"
          ;; Prepara o CallableStatement
          cstmt (.prepareCall conn sql)]
      (.registerOutParameter cstmt 1 Types/VARBINARY)
      (.registerOutParameter cstmt 2 Types/VARCHAR)
      (.registerOutParameter cstmt 3 Types/INTEGER)

      (let [s (.execute cstmt)]
        [(apply str (map #(format "%02x" %) (.getBytes cstmt 1)))
         (.getString cstmt 2)
         (.getInt cstmt 3)])))
```

Do you have any advice on how to make this code more 'Clojure way'?

Thank you for the work you've been doing for the community.

**Comment by seancorfield** [comment]
I'd probably do this, which cleans up a bit of the repetition:
```clojure
    cstmt (doto (.prepareCall conn sql)
            (.registerOutParameter 1 Types/VARBINARY)
            (.registerOutParameter 2 Types/VARCHAR)
            (.registerOutParameter 3 Types/INTEGER))
```
Or you could that up in a variadic function: `(defn callable [conn sql & types] ...)` and then it would look like:
```clojure
    cstmt (callable conn sql Types/VARBINARY Types/VARCHAR Types/INTEGER)
```
You'd still have to know the number and types of the parameters to retrieve the values afterward.

JDBC is inherently procedural and full of mutability so there's only so much you can do to paper over that.
