### ISSUE TITLE
Add DuckDB to next.jdbc.connection/dbtypes

### ISSUE THREAD

**Issue by mchampine** [seancorfield/next-jdbc#140]
DuckDB https://github.com/cwida/duckdb has a jdbc driver and works with next-jdbc using a db spec as in the following example:

```clojure
(def db
  {:classname "org.duckdb.DuckDBDriver"
   :dbtype    "duckdb"
   :host      :none
   :dbname    "duckdb.db"})
```

If next.jdbc.connection/dbtypes is updated with an entry for "duckdb" it will simplify use with next-jdbc.

For testing, [org.duckdb/duckdb_jdbc “0.2.1"] (lein) is current.
Note: auto increment is not implemented yet. Here's a modified version of the "getting started" code that removes auto_increment:

```clojure
(ns nextjdbc.core
  (:require [next.jdbc :as jdbc]
            [next.jdbc.sql :as jdbcsql]))

(def db
  {:classname "org.duckdb.DuckDBDriver"
   :dbtype    "duckdb"
   :host      :none
   :dbname    "duckdb.db"})
;; => #'nextjdbc.core/db

(def ds (jdbc/get-datasource db))
;; => #'nextjdbc.core/ds

(jdbc/execute! ds ["
create table address (
  id int primary key,
  name varchar(32),
  email varchar(255)
)"])
;; => [#:next.jdbc{:update-count 0}]

(jdbc/execute! ds ["
insert into address(id,name,email)
  values(1, 'Sean Corfield','sean@corfield.org')"])
;; => [#:next.jdbc{:update-count 0}]

(jdbc/execute! ds ["select * from address"])
;; => [{:id 1, :name "Sean Corfield", :email "sean@corfield.org"}]
```

**Comment by seancorfield** [comment]
I can only add `"duckdb"` to the list of known database types -- I can't add it as a fully-supported database because it won't run on my development machine (running macOS 10.12).
