### ISSUE TITLE
AS clause results in broken keys in result set

### ISSUE THREAD

**Issue by mchampine** [seancorfield/next-jdbc#141]
**Description**
Given a table "address" with column "name" a simple select using AS will generate invalid EDN as a response:

```clojure
;; example
(jdbc/execute! ds ["select name AS 'Broken Key' from address"])
;; [{:Broken Key "Sean Corfield"}]

nextjdbc.core> [{:Broken Key "Sean Corfield"}]
Syntax error reading source at (REPL:46:46).
Map literal must contain an even number of forms
```

**Expected behavior**
Not sure. I assume the fix would involve munging the key string to create a valid keyword. In this case, :brokenkey or :broken_key or :broken-key

**project.clj/deps.edn**
[seancorfield/next.jdbc "1.1.588"]
Appears to be the case with any driver.  Tested with sqlite and duckdb.

**Environment (please complete the following information):**
 - OS: MacOS
 - Java Version:  (AdoptOpenJDK)(build 1.8.0_202-b08)
 - Clojure Version: 1.10.1
 - Database: [org.xerial/sqlite-jdbc "3.32.3.2"] and [org.duckdb/duckdb_jdbc "0.2.1"]

**Comment by seancorfield** [comment]
That's expected: Clojure lets you create keywords from things that are not "readable". Not a bug in `next.jdbc` and not something that `next.jdbc` should try to "fix" for you.
```clojure
user=> [{(keyword "Broken Key") "Sean Corfield"}]
[{:Broken Key "Sean Corfield"}]
user=> 
```
