### ISSUE TITLE
Support for named parameters

### ISSUE THREAD

**Issue by aneilbaboo** [seancorfield/next-jdbc#145]
**Is your feature request related to a problem? Please describe.**
While ordered parameters are fine for relatively simple queries, they become unwieldy and error-prone for larger ones. 

**Describe the solution you'd like**
It would be nice to be able to provide a map instead of a vector.

Something like this:

```clojure
(jdbc/execute-one! conn
  ["UPDATE user SET address = :address, plan = :plan WHERE id = :id "
    {:address "123 main st", :plan "Basic", :id 123}])
```

**Comment by seancorfield** [comment]
This is out of scope for `next.jdbc` (it was out of scope for `clojure.java.jdbc` as well). HoneySQL lets you use named parameters: it will generate positional SQL/parameters from named parameters and a hash map.

**Comment by aneilbaboo** [comment]
Makes sense. Thanks.
