### ISSUE TITLE
how to escape ? as jsonb operator for postgresql query?

### ISSUE THREAD

**Issue by lanyusan** [seancorfield/next-jdbc#168]
? is a legitmate operator for jsonb in postgresql.

[postgresql jsonb](https://www.postgresql.org/docs/current/functions-json.html)

How to escape it in sql string for example ? 
` select * from blog where commenters ? 'julia' `?

**Comment by seancorfield** [comment]
See https://jdbc.postgresql.org/documentation/head/statement.html

**Comment by lanyusan** [comment]
Thanks
