### ISSUE TITLE
Class cast exception with nested jsonb_array_elements

### ISSUE THREAD

**Issue by zetafish** [seancorfield/next-jdbc#170]
The `next.jdbc.sql/query` throws a class cast exception when trying to run a query that involves nested `jsonb_array_elements`.

First I setting up the table and data and some query strings

```
(next.jdbc/execute! ds ["create table foo(data jsonb)"])
(next.jdbc.sql/insert! ds :foo {:data [{:name "city" :value ["london" "amsterdam"]}]})
(next.jdbc.sql/insert! ds :foo {:data [{:name "city" :value ["paris" "rome"]}
                                       {:name "mood" :value ["happy" "sad"]}]})

(def s1 "select jsonb_array_elements(data)->'value' as v from foo")
(def s2 "select jsonb_array_elements(jsonb_array_elements(data)->'value') as v from foo")
```

Then the following works for `clojure.java.jdbc`

```
(clojure.java.jdbc/query {:datasource ds} [s1]) ;; => ({:v ["london" "amsterdam"]} {:v ["paris" "rome"]} {:v ["happy" "sad"]})
(clojure.java.jdbc/query {:datasource ds} [s2]) ;; => ({:v "london"} {:v "amsterdam"} {:v "paris"} {:v "rome"} {:v "happy"} {:v "sad"})
```

But for `next.jdbc` the nested one fails:

```
(next.jdbc.sql/query ds [s1]) ;;=> [{:v ("london" "amsterdam")} {:v ("paris" "rome")} {:v ("happy" "sad")}]
(next.jdbc.sql/query ds [s2]) ;;=> throws with java.lang.ClassCastException
```

**Environment:**
 - Mac OS
 - Java: OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
 - Clojure: 1.10.3
 - next.jdbc:  [com.github.seancorfield/next.jdbc  {:mvn/version "1.2.674"}
 - postgres: org.postgresql/postgresql  {:mvn/version "42.2.22"}

**Comment by seancorfield** [comment]
Please provide the complete stacktrace, including the exact error.

**Comment by zetafish** [comment]
Whlle trying to get hold of the stacktrace I discovered the root cause. I had used the this function from the Tips&Tricks page

```
(defn <-pgobject
  "Transform PGobject containing `json` or `jsonb` value to Clojure
  data."
  [^org.postgresql.util.PGobject v]
  (let [type  (.getType v)
        value (.getValue v)]
    (if (#{"jsonb" "json"} type)
      (when value
        (with-meta (json/decode value true) {:pgtype type}))
      value)))
```

And then 

```
(extend-protocol rs/ReadableColumn
  org.postgresql.util.PGobject
  (read-column-by-label [^org.postgresql.util.PGobject v _]
    (<-pgobject v))
  (read-column-by-index [^org.postgresql.util.PGobject v _2 _3]
    (<-pgobject v)))
```

The problem was that the json decode returns a String and that one cannot have a meta on it. Removing the `with-meta` solved my problem.

The reason the clojure.java.jdbc did not have this problem is that I did not wrap it with meta.
