### ISSUE TITLE
Incorrect JDBC URL construction for H2

### ISSUE THREAD

**Issue by kelvinqian00** [seancorfield/next-jdbc#174]
When constructing a JDBC URL for H2 using `next.jdbc.connection/jdbc-url`, the resulting URL uses the incorrect property separator, namely colons instead of ampersands. ([H2 doc reference](http://www.h2database.com/html/features.html#database_url))

In addition, adding the `:property-separator` key to the param map adds an extraneous `property-separator` query param to the URL.

Code:
```clojure
(next.jdbc.connection/jdbc-url
 {:dbtype "h2:mem"
  :dbname "test_db"
  :host "localhost"
  :port 9001
  :user "my_user"
  :password "swordfish"})
```

Expected:
```clojure
=> "jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;USER=my_user;PASSWORD=swordfish
```

Actual:
```clojure
=> "jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1?user=my_user&password=swordfish
```

And this is the result when I add the kv-pair `:property-separator ";"` to the param map:
```clojure
=> "jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1?user=my_user&password=swordfish;property-separator=;
```

**Comment by seancorfield** [comment]
Thanks! Fix on *develop*. I'll probably cut a new release over the weekend with this fix.

**Comment by kelvinqian00** [comment]
Cool. However, I saw that you forgot to make `:property-separator` a keyword on this line: https://github.com/seancorfield/next-jdbc/blob/cc975f825dd9ee2993c43114b8f9454d00616feb/src/next/jdbc/connection.clj#L166

**Comment by seancorfield** [comment]
Ouch! Good catch, thank you! Glad I didn't get time to cut a new release with that bug still in it. Fixed on *develop*.

**Comment by seancorfield** [comment]
Version 1.2.709 is available with this fix.
