### ISSUE TITLE
Update/test against latest HikariCP

### ISSUE THREAD

**Issue by seancorfield** [seancorfield/next-jdbc#176]
Big update? com.zaxxer/HikariCP |      3.4.2 |                  5.0.0

**Comment by holyjak** [comment]
@seancorfield I'd be happy to help test HikariCP 5 against PostgreSQL

**Comment by seancorfield** [comment]
This isn't really a matter of testing against a single DB, this is more about whether `->pool` needs any updates to work with the latest HikariCP -- and to still stay compatible with c3p0.

**Comment by holyjak** [comment]
I am going to use ->pool with HikariCP 5 so I wil let you know if I run into anything. So far it seems to work fine.

**Comment by seancorfield** [comment]
At this point, I'm going to assume it "works" and close this out, on the grounds that anyone who runs into a problem will create a new issue.

**Comment by seancorfield** [comment]
Just an FYI: HikariCP 5.0.0 isn't compatible with JDK 8 and `next.jdbc` is still tested against that so I can't update the test version just yet.
