### ISSUE TITLE
Question: What it the minimal required version of Clojure?

### ISSUE THREAD

**Issue by holyjak** [seancorfield/next-jdbc#183]
Hi, what it the minimal required version of Clojure? Thank you!

**Comment by seancorfield** [comment]
Per Getting Started:

> It is designed to work with Clojure 1.10 or later, supports `datafy` / `nav`, and by default produces hash maps with automatically qualified keywords, indicating source tables and column names (labels), if your database supports that.

It's tested against 1.10.3 and 1.11 (master).

**Comment by holyjak** [comment]
OMG I see now it is very visible at https://cljdoc.org/d/com.github.seancorfield/next.jdbc/1.2.731/doc/getting-started#installation Sorry for not looking better!
