### ISSUE TITLE
IResultSetReadColumn replacement?

### ISSUE THREAD

**Issue by manuel-uberti** [seancorfield/next-jdbc#20]
Hi,

first of all thanks for `next-jdbc`.

I'm giving it a try on a personal project where I was using `clojure.java.jdbc`. The database the project uses is PostgreSQL, and I use `hikari-cp` for the connection pool.

One thing I am doing right now is the following:
```
(extend-protocol jdbc/IResultSetReadColumn
  Date
  (result-set-read-column [v _ _]
    (-> v
        jl/local-date
        dates/format-date))

  Timestamp
  (result-set-read-column [v _ _]
    (-> v
        jl/local-date
        dates/format-date))

  PGobject
  (result-set-read-column [pgobj _metadata _index]
    (let [type  (.getType pgobj)
          value (.getValue pgobj)]
      (case type
        "json" (cheshire/parse-string value true)
        "jsonb" (cheshire/parse-string value true)
        "citext" (str value)
        value))))
```
Basic transformations on the data in the ResultSet. What is the suggested way to do something similiar with `next-jdbc`?

**Comment by seancorfield** [comment]
Per the docs: https://cljdoc.org/d/seancorfield/next.jdbc/1.0.0-alpha13/api/next.jdbc.result-set#ReadableColumn

See also: https://cljdoc.org/d/seancorfield/next.jdbc/1.0.0-alpha13/doc/migration-from-clojure-java-jdbc#further-minor-differences

**Comment by manuel-uberti** [comment]
Thank you!
