### ISSUE TITLE
Returning Clause Documentation Typo

### ISSUE THREAD

**Issue by dharrigan** [seancorfield/next-jdbc#202]
Hi! I think there may be a slight typo, here: 

https://cljdoc.org/d/com.github.seancorfield/honeysql/2.2.868/doc/getting-started/postgresql-support#returning, 

namely the example of `(returning [:did :dname])`. 

I believe in the documentation https://cljdoc.org/d/com.github.seancorfield/honeysql/2.2.868/api/honey.sql.helpers#returning, 

it's `(returning & cols)`, so should it be `(returning :did :dname)`?

At least, the later works for me, not the former :slightly_smiling_face:

-=david=-

**Comment by seancorfield** [comment]
I think this issue was meant to be this issue over on HoneySQL? https://github.com/seancorfield/honeysql/issues/399
