### ISSUE TITLE
Provide specs for main API

### ISSUE THREAD

**Issue by seancorfield** [seancorfield/next-jdbc#21]
Per https://clojureverse.org/t/next-jdbc-early-access/4091/31 -- add specs and document how to use them.

Provide an `instrument` function in the `next.jdbc.specs` namespace to make it easy to instrument the API.

Consider doing the same for `next.jdbc.sql.specs`.

**Comment by seancorfield** [comment]
@holyjak How does https://github.com/seancorfield/next-jdbc/blob/master/doc/getting-started.md#support-from-specs look?

**Comment by holyjak** [comment]
very good! thank you!

**Comment by seancorfield** [comment]
This will be in Beta 1, coming soon.
