### ISSUE TITLE
ReadableColumn protocol could use args re-ordered

### ISSUE THREAD

**Issue by corasaurus-hex** [seancorfield/next-jdbc#218]
**Describe the bug**

The order of args in the call to `(defprotocol ReadableColumn ....` makes both emacs and intellij unhappy.

https://github.com/seancorfield/next-jdbc/blob/develop/src/next/jdbc/result_set.clj#L109-L131

**To Reproduce**

You can see the difference in emacs between the ReadableColumn protocol and the RowBuilder protocol, that in RowBuilder it sees the docstring as a docstring.

![20220828170115-yjpsw-result_set clj – Doom Emacs](https://user-images.githubusercontent.com/130/187096184-b79bd634-d4eb-4236-9f87-63aa13d77030.png)

In intellij it's much more dire because it messes with resolution of functions and classes in the definition and also interferes with locations that call this function:

![20220828170314-gf2jm-next-jdbc – n j result-set](https://user-images.githubusercontent.com/130/187096314-1f8656f8-4971-4a9b-ae2e-0fb588fefd8e.png)

![20220828170720-waofa-darn](https://user-images.githubusercontent.com/130/187096379-1499b823-3b5d-4802-af20-2cee94cfa550.png)

The issue appears to be that both editors expect `:extend-via-metadata true` to come after the docstring, not before. The [docs seem to indicate this is the expected order](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defprotocol), too, which is probably why the editors are expecting this order even though clojure seems to accept either order.

**Expected behavior**

Expected the protocol to render correctly and for editors to support how they're defined.

**Stacktraces**

Not relevant.

**project.clj/deps.edn**

Not really relevant.

**Environment (please complete the following information):**

I guess this could be relevant?

 - OS: MacOS
 - Java Version: Temurin-17.0.2+8
 - Clojure Version: 1.11.1
 - Database: postgres
 - Driver Library Version: org.postgresql/postgresql

**Additional context**

None.

**Comment by seancorfield** [comment]
Interesting edge case. Thanks!
