### ISSUE TITLE
Document caveats around PostgreSQL exception handling

### ISSUE THREAD

**Issue by sheluchin** [seancorfield/next-jdbc#226]
Hi, @seancorfield. You gave me some advice about exception handling in next.jdbc the other day on [Slack](https://clojurians.slack.com/archives/C1Q164V29/p1663599900485379) and we discovered that PostgreSQL has a non-standard way of dealing with exceptions. Specifically, it doesn't use the standard [SQL exception hierarchy](https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/package-tree.html), but just throws `PSQLException`. This is likely to be the case until https://github.com/pgjdbc/pgjdbc/pull/1904 gets merged.

You asked me to open an issue here to remind you to mention this in the Tips and Tricks section of the docs to help any next.jdbc users which might be using or considering Postgres.

Thanks for your help!

**Comment by seancorfield** [comment]
I dug into this a bit and the whole area is pretty vendor-specific, so I've written up a new section in **Tips & Tricks** that covers exception handling _in general_ rather than try to offer database-specific advice.

**Comment by sheluchin** [comment]
@seancorfield Thank you for looking into this and providing some guidance. Sounds like a complicated situation indeed, but the content you added is helpful as a basis.

**Comment by seancorfield** [comment]
Yeah, when I started reading various JDBC driver docs and experimenting in the REPL with the various ones I test against, I realized that it was way worse than our discussion on Slack suggested! 😱
