### ISSUE TITLE
[feature] PostgreSQL COPY

### ISSUE THREAD

**Issue by kwladyka** [seancorfield/next-jdbc#234]
**Is your feature request related to a problem? Please describe.**
`COPY` is the faster way to write a lot of data to DB. Much more faster, than `INSERT`. With writing a lot of data to DB it makes a really big difference in performance.

**Describe the solution you'd like**
Add `COPY` support with `STDIN` and `BINARY`. But while doing this it is very reasonable to add support for all FORMAT (BINARY / CSV / TEXT) and FROM / TO (STDIN / STOUT / PROGRAM / filename).

As I understand `BINARY` need extra support for data types. But it is gives the fastest way to write do DB as possible. As far as I know there is nothing faster, than that.

**Describe alternatives you've considered**
There is https://github.com/jgdavey/clj-pgcopy but it is not maintained anymore. Last commit is 2 years ago. But https://github.com/jgdavey/clj-pgcopy/blob/main/src/clj_pgcopy/core.clj can be good place to learn about `COPY`.

I consulted the best way to write a lot of data to PostgreSQL on PostgreSQL slack and they are very clear about this solution as the right one and the most performant one. Definitely `COPY` instead of `INSERT`.

**Additional context**
PostgreSQL official documentation
https://www.postgresql.org/docs/current/sql-copy.html

**Comment by seancorfield** [comment]
PostgreSQL-specific. Not appropriate for `next.jdbc`.
