### ISSUE TITLE
Error when calling 4-arity sql/insert-multi! with empty/nil hash-maps-or-cols and non-empty opts-or-rows

### ISSUE THREAD

**Issue by prook** [seancorfield/next-jdbc#235]
**Describe the bug**
When calling 4-arity `sql/insert-multi!` with empty/nil `hash-maps-or-cols` (3rd) parameter and non-empty `opts-or-rows` (4th) parameter, an AssertionError is thrown.

This behavior is inconsistent with other parameter combinations; All other invocations short-circuit when supplied with an empty coll of things to insert, returning an empty vector (without ever entering the sql query construction machinery).

**To Reproduce**

```clojure
(require '[next.jdbc.sql :as sql])

(def conn :we-dont-even-need-a-connection-for-this)

;; 3-arity
(sql/insert-multi! conn :mytable [])
;; => []

;; 4-arity invocation, 4th param (rows-or-opts) is empty
(sql/insert-multi! conn :mytable [] {})
;;=> []

;; 4-arity invocation, 4th param (rows-or-opts) is not empty
(sql/insert-multi! conn :mytable [] {:batch true})
;; Execution error (AssertionError) at next.jdbc.sql.builder/for-insert-multi (builder.clj:147).
;; Assert failed: column counts are not consistent across cols and rows
;; (apply = (count cols) (map count rows))

;; 5-arity invocation, 5th param (opts) is empty
(sql/insert-multi! conn :mytable [:mytable/id :mytable/mycol] []  {})
;; => []

;; 5-arity invocation, 5th param (opts) is empty
(sql/insert-multi! conn :mytable [:mytable/id :mytable/mycol] []  {:batch true})
;; => []
```

**Expected behavior**

All the calls listed above should behave the same, i.e., return `[]`.

**deps.edn**
```edn
{:deps {com.github.seancorfield/next.jdbc       {:mvn/version "1.3.847"}}}
```

**Comment by prook** [comment]
Hmmm, after instrumenting API spec checks, it is clear that the `:with-hash-maps` flavor of `sql/insert-multi!` does not support empty `hash-maps` param deliberately, meaning that the first two calls in the repro section throw as well.

**Comment by seancorfield** [comment]
I'll update the spec and make the calls consistent. Thanks for the detailed bug report!

**Comment by prook** [comment]
I even have a insert-multi! patch ready (+ tests), but I'm not friends with spec, so I'd probably botch that.

**Comment by seancorfield** [comment]
I've looked into this and there's no easy way to short-circuit the "no rows" case so the fact that it "works" without spec-instrumentation in those first two cases is an accident of the implementation, and the spec is correct: you cannot call `insert-multi!` with empty rows.

So I'm going to close this "as designed" and assert you wandered into undefined behavior territory. Sorry.

**Comment by prook** [comment]
I understand the resolution, and I can work around this quirk.

I've also looked back at my attempt at fixing the problem in the 4-arity of insert-multi!. I must admit the solution was biased towards the hash-maps flavor, and would probably break some corner-cases of the cols+rows flavor.

I'm not very happy with the user experience though. It took me hours (and you as well) to figure this out, which should have been time spent doing productive work. Ideally, this should not happen in unsuspecting-user-facing APIs, and I wish I was able to to save someone else the trouble.

**Comment by seancorfield** [comment]
Well, it took me hours to figure out whether I can easily change the Spec and the behavior without breaking other things 😸 

But I will probably take another look at this at some point, as having a "multi" operation short-circuit to do nothing when given an empty sequence mostly makes sense (an example of when it doesn't is `col IN <sequence of values>` which HoneySQL has to deal with and specifically disallow, requiring user code to guard against empty sequences -- which is why I'm leaning to the same "default" here).

I need to check how `execute-batch!` handles empty sequences and look at other parts of the `next.jdbc` API too.
