### ISSUE TITLE
Dead link to JDBC PostgreSQL arrays docs

### ISSUE THREAD

**Issue by p-himik** [seancorfield/next-jdbc#241]
The page at https://cljdoc.org/d/com.github.seancorfield/next.jdbc/1.3.847/doc/getting-started/tips-tricks?q=array#working-with-arrays links to [PostgreSQL™ Extensions to the JDBC API](https://jdbc.postgresql.org/documentation/head/arrays.html) but it's 404 now.

Seems like the link should be https://jdbc.postgresql.org/documentation/server-prepare/#arrays now.
And also the mentioned 7 types should probably be changed to 8 types.

**Comment by seancorfield** [comment]
Thanks!
