### ISSUE TITLE
clojure.java.jdbc compatibility in concurrent connection usage

### ISSUE THREAD

**Issue by seancorfield** [seancorfield/next-jdbc#245]
**Is your feature request related to a problem? Please describe.**
See #244 for background.

**Describe the solution you'd like**
If you bind `*nested-tx*` to `:ignore` to get c.j.j compatibility there, you should also get compatibility on the (non-)locking of `Connection` to match c.j.j's unsafe behavior (see #106 for why that changed in the first place).

**Comment by seancorfield** [comment]
@camsaul this is on **develop** and in the latest 1.3.999-SNAPSHOT for testing.

**Comment by camsaul** [comment]
Thanks, I'll give it a shot tomorrow!

**Comment by camsaul** [comment]
Thanks @seancorfield, the fix works for us! 🥳
