### ISSUE TITLE
Unable to specify no port

### ISSUE THREAD

**Issue by vemv** [seancorfield/next-jdbc#248]
Hi!

I'm using `(jdbc.connection/jdbc-url)` to build URLs which are expected to look like this:

https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/6c8dce78b10382a20f407112ca204aaa4f0ac19b/docs/jdbc-postgres.md?plain=1#L38

i.e. there should no port, so the first few characters of the produced url should be `jdbc:postgresql:///`.

I'm unable to specify this using the expected db-spec format. `jdbc:postgresql://:5432/` is produced instead. Because that library's role is to provide some sort of dynamic network connection, a fixed port could plausibly be problematic.

This was my attempt + workaround via `string/replace`:

```clj
(-> {:host ""
     :dbname "the-db-name"
     :dbtype "postgres"
     :port ""
     :user "postgres"
     :password "123"
     :cloudSqlInstance "foo-123:us-central1:the-instance-name"
     :socketFactory "com.google.cloud.sql.postgres.SocketFactory"
     :enableIamAuth "true"}
    (jdbc.connection/jdbc-url)
    (string/replace "://:/" ":///"))
```

It would seem reasonable not to fallback to `5432` if a explicit nil value was provided? One could say, fallback values typically are the role of a config lib like Aero.

Thanks - V

**Comment by vemv** [comment]
FWIW, a special value like `:nil` could prevent any unintended complexity / surprises for other users.

**Comment by seancorfield** [comment]
There's precedent for `:none` which can be specified for `:host` to exclude it from the JDBC URL. I'll add a similar condition for `:port` and make a pass over the docs to ensure both are clear/supported.

**Comment by vemv** [comment]
Fantastic, thank you!
