### ISSUE TITLE
Add active-tx? predicate

### ISSUE THREAD

**Issue by seancorfield** [seancorfield/next-jdbc#254]
**Is your feature request related to a problem? Please describe.**
See Slack thread https://clojurians.slack.com/archives/C1Q164V29/p1686391284927709

TL;DR: it is desirable to be able to write functions that can detect (and throw) if they are called outside a `next.jdbc` "transaction" context.

**Describe the solution you'd like**
A predicate in the API that indicates whether `next.jdbc` thinks it has an active TX.

Actively document the artificial nature of transactions somewhere (and especially in this new predicate) -- see comments in that thread!

**Describe alternatives you've considered**
Raw Java interop (per that thread) -- but just being auto-commit: false isn't really sufficient and isolation-level doesn't tell you enough.

**Comment by lukaszkorecki** [comment]
Because I had to write java interop before to figure this out - having a direct (and way better informed) support in `next.jdbc` would be amazing - it helps library users being better informed and understand all of the edge cases of using transactions.
