### ISSUE TITLE
clojure.java.jdbc to next.jdbc migration

### ISSUE THREAD

**Issue by dharrigan** [seancorfield/next-jdbc#263]
Hi,

I'm doing a clojure.java.jdbc to next.jdbc migration and I thought it might be useful to highlight anything that I discover during this process. After a little discussion with your fine self, you asked if I could create a "holding" issue with particular issues raised when identified.

This is the holding issue :-)

I'll raise individual issues and link to this one as I come across things.

-=david=-

**Comment by seancorfield** [comment]
Anything to add at this point?

**Comment by dharrigan** [comment]
Hi,

I think we're good - looks like the migration points was miminal for me! :-)

-=david=-
