### ISSUE TITLE
Postgres column names are always lowercase.

### ISSUE THREAD

**Issue by se-neaxplore** [seancorfield/next-jdbc#266]
**Describe the bug**
Queriying a postgres database, the column name casing is not preserved.

**To Reproduce**

```sql

CREATE Table user1 (
    id uuid default gen_random_uuid(),
    user_id uuid,
    name text,
    PRIMARY KEY (id)
);

INSERT INTO user1 (
  user_id, name 
) VALUES 
  ( '3f10578f-6e3e-4c15-b77b-490b8b9ea8b1', 'user' );



CREATE Table user2 (
    id uuid default gen_random_uuid(),
    userId uuid,
    name text,
    PRIMARY KEY (id)
);


INSERT INTO user2 (
  userId, name 
) VALUES 
  ( '3f10578f-6e3e-4c15-b77b-490b8b9ea8b1', 'user' );

```
Running the following queries:

```clojure
(j/execute! db ["select user_id as userId from user1"])

;; => [#:user1{:userid #uuid "3f10578f-6e3e-4c15-b77b-490b8b9ea8b1"}]


(j/execute! db ["select user_id as userId from user1"] {:builder-fn rs/as-unqualified-maps})

;; => [{:userid #uuid "3f10578f-6e3e-4c15-b77b-490b8b9ea8b1"}]


(j/execute! db ["select userId from user2"] )

;; => [#:user2{:userid #uuid "3f10578f-6e3e-4c15-b77b-490b8b9ea8b1"}]

(j/execute! db ["select userId from user2"] {:builder-fn rs/as-unqualified-maps})

;; => [{:userid #uuid "3f10578f-6e3e-4c15-b77b-490b8b9ea8b1"}]


(j/execute! db ["select userId as userId from user2"] {:builder-fn rs/as-unqualified-maps})

;; => [{:userid #uuid "3f10578f-6e3e-4c15-b77b-490b8b9ea8b1"}]
```
**Expected behavior**

The column names should be preserved, or respect the `AS` name.

From the docs: 

as-unqualified-maps -- simple keywords as-is, e.g., :ID, :firstName,

https://github.com/seancorfield/next-jdbc/blob/develop/doc/result-set-builders.md

**deps.edn**

```clojure
{:deps {
    org.clojure/clojure {:mvn/version "1.11.1"}
    com.github.seancorfield/next.jdbc {:mvn/version "1.3.894"}
    org.postgresql/postgresql {:mvn/version "42.6.0"}}}
````
**Environment:**
 - OS: Linux
 - Java Version: java 21.0.1 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)
 - Clojure Version: 1.11.1
 - Database: postgres:15.2-alpine
 - Driver Library Version:  org.postgresql/postgresql {:mvn/version "42.6.0"}

**Comment by seancorfield** [comment]
If you are using the default result set builder, what you get back from `next.jdbc` is what the JDBC driver provides as table and column names.

If you are using `as-unqualified-maps`, what you get back from `next.jdbc` is what the JDBC driver provides as column names.

Only if you use the `-lower` variant builders will `next.jdbc` attempt to lower-case anything.

Given that you are not stropping the column names in the DDL or aliases in the SQL, I would actually expect them to come back as lowercase with several databases (and as UPPERCASE with others).

**Comment by se-neaxplore** [comment]
Thank you for your fast answer, but I have hard time understanding this issue.

So it is a JDBC driver issue and not a next.jdbc one?

I don't understand what you mean with the last part your answer. I used the `AS`  alias keyword.

Because this leads to following unintuitive behaviour:

```clojure
(j/execute! machine-hub-db ["select user_id as userId, name as userid from user1"])

;; => [#:user1{:userid "Ju.Ser@nea.de"}]

```
And this works for example in pgadmin.

![image](https://github.com/seancorfield/next-jdbc/assets/65458631/4142fdab-267b-4e71-bf83-efdf519d19f7)

**Comment by seancorfield** [comment]
SQL is not case-sensitive by definition (although some databases violate this definition). Some databases (and their drivers) behave as if everything were UPPERCASE (e.g., H2), some databases (and their drivers) behave as if everything were lowercase. A few have some aspects of case sensitivity -- MySQL treats table names as case sensitive _if the host O/S is case sensitive_ but treats column names as case insensitive (so MySQL table names are case sensitive on Linux, but case insensitive on Windows and macOS!).

The way to get case sensitivity is to strop the identifiers (quote them) in the DDL and SQL.

None of this is happening in `next.jdbc` -- this is just how databases and their drivers work.

**Comment by se-neaxplore** [comment]
Big thanks for the detailed answer and taking the time to break it down. It was super helpful.

Appreciate it!
