### ISSUE TITLE
Can `SQLLogging` implement `Closeable`?

### ISSUE THREAD

**Issue by gravieure** [seancorfield/next-jdbc#270]
**Is your feature request related to a problem? Please describe.**

I want to log every query executed on a connection.  I have code similar to:

```clojure
(with-open [conn (jdbc/get-connection "jdbc:mysql://root@localhost/mysql")]
  ...)
```

Which I changed to:

```clojure
(defn log-sql! [operation query+args]
  (log/infof "SQL: %s %s" operation query+args))

(with-open [conn (-> (jdbc/get-connection "jdbc:mysql://root@localhost/mysql")
                     (jdbc/with-logging log-sql!))]
  ...)
```

However, this throws `IllegalArgumentException` when `with-open` unwinds, because `next.jdbc.sql_logging.SQLLogging` doesn't implement `Closeable`.

**Describe the solution you'd like**

I'd like to have a way to enable query logging either globally or per-connection.  I don't have a preference on the technical implementation.

If `SQLLogging`  can implement `Closeable`, that'd work fine: I can wrap `jdbc/with-connection` with code that enables logging (or not) based on a configuration.

Configuring in the ds-spec given to `jdbc/with-connection` would also work fine, as would binding a dynamic var to control logging.

I'd just like a way to do this without needing to update every call site that uses the database.

**Describe alternatives you've considered**

I could wrap the datasource at the call site, but this is a lot of legwork and has the potential for inconsistency; a programmer might forget or not find a callsite, leading to incomplete logs.

I looked at the logging support in MySQL Connector/J, but it needs slf4j, which I'm not using in my project.  I'd prefer not to add it.

Server-side query logs are hard to set up and access, and may include queries from other software than what I'm working on, so that's not a great fit either.

**Additional context**

It looks like there's some complexity around pooling, which might be why this isn't already implemented.  Skimming the code, it looks like some pooling libraries don't implement `Closeable`, which I can see lowering the common denominator of what `SQLLogging` can support.

I'm not using pooling, but I understand why pools not supporting `Closeable` could influence the current state of things.

**Comment by gravieure** [comment]
Quick followup:  I solved my immediate problem by dealing with the MySQL Connector/J logging stuff. 

I still think it'd be nice if next.jdbc could do per-connection query logging (or maybe it can, and I'm doing it wrong?), since this would let you configure it in a uniform way, rather than needing to deal with the specifics of the particular JDBC implementation(s).

**Comment by seancorfield** [comment]
The docs for `with-logging` (and `with-options`) are pretty clear about needing to rewrap raw `Connection` objects inside `with-open` calls -- there's an explicit example for `with-options` -- and the docs explicitly call out the fact that `get-connection` (and `get-datasource`) return plain Java objects and that you cannot do Java interop on the result of either `with-options` or `with-logging`.

As far as I'm aware, there's no standard for JDBC logging -- which is why `with-logging` exists -- so you either have to do something driver-specific via JDBC or live with the restrictions of `with-logging` as documented. Sorry.
