### ISSUE TITLE
Easier counting with `next.jdbc.sql/find-by-keys`

### ISSUE THREAD

**Issue by vemv** [seancorfield/next-jdbc#274]
**Is your feature request related to a problem? Please describe.**

I'd like to sql-`count` more easily while using `find-by-keys`.

I can pass `:columns [["count(*)" :total]]` and then `-> ,,, first :total` the result.

But neither bit seems intuitive to me.

**Describe the solution you'd like**

An option in `find-by-keys` that translates to a count, maybe?

**Describe alternatives you've considered**

A separate function in the same ns that takes similar options to `find-by-keys`, but that performs a count and returns a number (the count) rather than a coll of results.

Thanks - V

**Comment by seancorfield** [comment]
I'll think about it -- I really don't want to expand the "Friendly SQL Functions": I'd rather folks used HoneySQL for more complex SQL and `plan/select-one!` to get a single column value out of a result set.

**Comment by vemv** [comment]
Yes, agreed. I much appreciate Honey but in my current context, socially we decided to stick to `next.jdbc.sql` for the time being.

**Comment by seancorfield** [comment]
How would you feel about this:

```clojure
(aggregate-by-keys ds :table "count(*)" :total where-map opts)
;; would call:
(-> (find-by-keys ds :table where-map (assoc opts :columns [["count(*)" :total]])) first :total)
```

This would allow for more general aggregation. Perhaps the alias keyword (`:total` here) could be some weird, internal gensym'd name so you didn't need to specify it at all...?

**Comment by vemv** [comment]
Yes the `:total` would seem like some friction for users.

Other than that, it looks reasonable to me!

**Comment by vemv** [comment]
Nice, thank you!
