### ISSUE TITLE
Allow transactions on distinct connections in the same thread

### ISSUE THREAD

**Issue by mbezjak** [seancorfield/next-jdbc#282]
**Is your feature request related to a problem? Please describe.**

```clojure
(jdbc/with-transaction [tx1 data-source-1]
  (jdbc/execute! tx1 ,,,)
  (jdbc/with-transaction [tx2 data-source-2]
    (jdbc/execute! tx2 ,,,)
    (throw (Exception. "An exception happened, so rollback tx2"))))
```

Should open two separate transactions because those are two separate data sources, with two separate SQL connections. They just happen to execute in the same thread. `tx2` should be rolled back due an exception.

Right now, the above snippet is equivalent to

```clojure
(jdbc/with-transaction [tx1 data-source-1]
  (jdbc/execute! tx1 ,,,)
  (jdbc/execute! data-source-2 ,,,)
  (throw (Exception. "An exception happened, so it'll rollback tx1")))
```

More context: https://clojurians.slack.com/archives/C1Q164V29/p1720188613556859?thread_ts=1720104756.702669&cid=C1Q164V29

**Describe the solution you'd like**

`next.jdbc.transaction/*active-tx*` should probably be a hash-map java.sql.Connection -> boolean, or simply a hash-set of `java.sql.Connection` objects.

Implementing `java.sql.Connection` is usually done with proxies, so the key to the map above (element in a set) should probably be the [result of `unwrap` call](https://docs.oracle.com/en%2Fjava%2Fjavase%2F21%2Fdocs%2Fapi%2F%2F/java.sql/java/sql/Wrapper.html). Doing the same to [`javax.sql.DataSource`](https://docs.oracle.com/en%2Fjava%2Fjavase%2F21%2Fdocs%2Fapi%2F%2F/java.sql/javax/sql/DataSource.html) might be needed.

For backwards compability, `next.jdbc/active-tx?` should return `true` if the hash-map/hash-set is not empty. 1-arity variant accepting a `transactable` could be introduced.

**Describe alternatives you've considered**

I haven't yet started thinking about how to solve the problem above.

**Comment by mbezjak** [comment]
I got sidetracked a bit by other things. This is still on my mind. As soon as I have the time, I'll come back to this.

**Comment by mbezjak** [comment]
FYI: This is a variant (not merged yet) that we'll likely use in production. I'll report back after we've run it for a while and if we don't see any problems there.

```
(ns something
  (:require
   [next.jdbc.protocols :as p]
   [next.jdbc.transaction :as tx])
  (:import
   (java.sql Connection)
   (javax.sql DataSource)))

(defonce ^:private ^:dynamic *active-tx* #{})

(defn transact [con body-fn opts]
  (@#'tx/transact* con body-fn opts))

(extend-protocol p/Transactable
  java.sql.Connection
  (-transact [this body-fn opts]
    (let [raw (if (.isWrapperFor this Connection)
                (.unwrap this Connection)
                this)]
      (if (contains? *active-tx* raw)
        (body-fn this)
        (binding [*active-tx* (conj *active-tx* raw)]
          (transact this body-fn opts)))))

  javax.sql.DataSource
  (-transact [this body-fn opts]
    (let [raw (if (.isWrapperFor this DataSource)
                (.unwrap this DataSource)
                this)]
      (if (contains? *active-tx* raw)
        (with-open [con (p/get-connection this opts)]
          (body-fn con))
        (binding [*active-tx* (conj *active-tx* raw)]
          (with-open [con (p/get-connection this opts)]
            (transact con body-fn opts)))))))
```

Note that the code above was simplified by assuming the `:ignore` value of `*nested-tx*`.

**Comment by seancorfield** [comment]
@mbezjak Seems strange to track `DataSource` objects instead of `Connection` objects in that second case -- each time you call `get-connection` on a DS, you'll get a distinct, new `Connection` object.

**Comment by mbezjak** [comment]
@seancorfield You are right, of course!

With the code above, the following tests would fail:

```clojure
(try
  (jdbc/with-transaction [tx1 data-source]
    (insert-into-foo tx1)
    (jdbc/with-transaction [tx2 tx1]
      ;; Running this SQL shouldn't commit anything! It's as if `with-transaction` block is not
      ;; there at all.
      (is (= 1 (count-foo tx2))))
    (throw (Exception. "rollback outer!")))
  (catch Exception _))
(is (= 0 (count-foo data-source)))
```

and

```clojure
(jdbc/with-transaction [tx1 data-source]
  (is (= 0 (count-foo tx1)))
  (try
    (jdbc/with-transaction [tx2 data-source]
      (insert-into-foo tx2)
      (is (= 1 (count-foo tx2)))
      ;; tx2 is a transaction on its own that can be rollbacked. tx1 shouldn't see anything that
      ;; happened in tx2.
      (throw (Exception. "rollback inner!")))
    (catch Exception _)))
  (is (= 0 (count-foo data-source)))
```

(I know about `{:rollback-only true}` opt, but I went with exceptions anyway.)

With that in mind, the updated Transactables:

```clojure
(ns something
  (:require
   [next.jdbc.protocols :as p]
   [next.jdbc.transaction :as tx])
  (:import
   (java.sql Connection)))

(defonce ^:private ^:dynamic *active-tx* #{})

(defn transact [con body-fn opts]
  (@#'tx/transact* con body-fn opts))

(extend-protocol p/Transactable
  java.sql.Connection
  (-transact [this body-fn opts]
    (let [raw (if (.isWrapperFor this Connection)
                (.unwrap this Connection)
                this)]
      (if (contains? *active-tx* raw)
        (body-fn this)
        (binding [*active-tx* (conj *active-tx* raw)]
          (transact this body-fn opts)))))

  javax.sql.DataSource
  (-transact [this body-fn opts]
    (with-open [con (p/get-connection this opts)]
      (p/-transact con body-fn opts))))
```

:point_up: is really simple without `*nested-tx*`.

As before, we haven't merged any of this yet. It's all waiting for me to play around with transactions some more. I'll report back after we've run it for a while and if we don't see any problems.

**Comment by mbezjak** [comment]
Merged 3 weeks ago. No issues so far. :smile:

**Comment by seancorfield** [comment]
Can you check the latest SNAPSHOT or git deps works for you?

Based on your code, I've implemented the whole `*nested-tx*` behavior on top of your implementation.

**Comment by mbezjak** [comment]
Sure! Thanks for the changes!

The commits look good to me. All the tests pass with version `1.3.999-20241121.060628-115` (as of now, latest SNAPSHOT). I've pushed those changes to our `test` environment. They'll be running there for a few days. I'll let you know if there are any problems. Silence means: running just fine. :smile: 

Btw. we have a few next.jdbc-level tests that cover this new functionality. I can port that over to next.jdbc if you want. It comes down to retranslating those tests to fit what's already in `next.jdbc-test`.

**Comment by seancorfield** [comment]
> Btw. we have a few next.jdbc-level tests that cover this new functionality. I can port that over to next.jdbc if you want. It comes down to retranslating those tests to fit what's already in next.jdbc-test.

Sure! Feel free to send a PR if you find the time -- always good to have more tests.

**Comment by mbezjak** [comment]
I'll try to squeeze in the tests sometime this week.

Thanks for the change! Btw. The snapshot version ran in our `test` environment for a while. No problems whatsoever.
