### ISSUE TITLE
Pathlogical performance in pgsql for `WHERE col = ANY(?)`

### ISSUE THREAD

**Issue by bgrabow** [seancorfield/next-jdbc#283]
**Describe the bug**
This is about a performance bug in Postgres itself that is likely to be encountered when following the documentation in next.jdbc.

When filtering query results using `WHERE col = ANY(?)`, if the array of values contains exactly one item the query can encounter pathologically bad performance that takes orders of magnitude longer to complete compared to the same query with more than one item in the array of values. Detailed explanation can be found in this [article](https://pganalyze.com/blog/5mins-postgres-performance-in-vs-any) and this [pgsql bug report](https://www.postgresql.org/message-id/flat/17922-1e2e0aeedd294424%40postgresql.org).

The next.jdbc documentation helpfully [suggests](https://github.com/seancorfield/next-jdbc/blob/develop/doc/tips-and-tricks.md#postgresql) the use of `WHERE col = ANY(?)`. 

**To Reproduce**
Reproduction steps documented in the [pgsql issue](https://www.postgresql.org/message-id/flat/17922-1e2e0aeedd294424%40postgresql.org).

**Expected behavior**
The next.jdbc [documentation](https://github.com/seancorfield/next-jdbc/blob/develop/doc/tips-and-tricks.md#postgresql) should either mention the pathological performance of `WHERE col = ANY(?)` or suggest another alternative.

Here's one alternative that I'm using to avoid the performance bug:

```clojure
["SELECT * 
  FROM table
  WHERE col IN (select unnest(array(select jsonb_array_elements_text(?))))"
 vals]
```

There are probably other/better alternatives too.

**Comment by seancorfield** [comment]
I don't use PostgreSQL so I rely on the community for handling bugs in that database/driver. Feel free to submit a PR against the documentation.
