### ISSUE TITLE
Columns out of order (MS SQL Server)

### ISSUE THREAD

**Issue by Prometheus77** [seancorfield/next-jdbc#286]
**Describe the bug**
Result set map returned by `(execute! ds ["select x1, ... xn from table"])` on an MS SQL Server DB has columns out of order

**To Reproduce**
I encountered this problem on a proprietary company database and therefore cannot provide the reprex code

**Expected behavior**
Result set map columns are returned in the order indicated by the `select` statement

**Stacktraces**
NA

**project.clj/deps.edn**
```{clojure}
(defproject clj-adhoc "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.11.1"]
                 [com.github.seancorfield/next.jdbc "1.3.955"]
                 [com.microsoft.sqlserver/mssql-jdbc "12.8.1.jre11"]
                 [clojure.java-time "1.4.2"]
                 [scicloj/tablecloth "7.029.2"]]
  :main clj-adhoc.core
  :repl-options {:init-ns clj-adhoc.core})
```

**Environment**
 - OS: Windows 10 Pro Version 22H2 Installed on 12/‎20/‎2021 OS build 19045.5073 Experience	Windows Feature Experience Pack 1000.19060.1000.0
 - Java Version: openjdk 21.0.4 2024-07-16 LTS, OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS), OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)
 - Clojure Version: 1.10.3
 - Database: MS SQL Server 15.0.4395.2
 - Driver Library Version: [com.microsoft.sqlserver/mssql-jdbc "12.8.1.jre11"] with mssql-jdbc_auth-12.8.1.x64.dll

**Comment by seancorfield** [comment]
`next.jdbc` returns hash maps which are inherently unordered, and has never promised any column ordering. If you use an array result builder, you **will** get the column values in the SQL natural ordering (per the docs).

If you use `plan`, you can call `column-names` inside your reducing function and that will return the columns in the natural SQL order (again, per the docs).
