### ISSUE TITLE
Distro packaging

### ISSUE THREAD

**Issue by jcharaoui** [seancorfield/next-jdbc#289]
I'm working on packaging next-jdbc for Debian, and I notice that it's not possible to build the library from the GitHub tarball.

A lot of Clojure packages ship either (or both) a POM file or `project.clj` (Leiningen) file, and this makes it easier for us to ship software in distributions.

Thanks!

**Comment by seancorfield** [comment]
First off, Clojure libraries are normally distributed via a Maven-like repository and most libraries are already on clojars.org with some on Maven Central. That's how Clojure development tools expect to find dependencies. Even in those repositories, the JAR files that are distributed are source-based, not compiled.

Second, the Clojure community has increasingly shifted to using the official Clojure CLI, where dependencies are specified in `deps.edn` files, and the "build program" is specified in `build.clj` -- Clojure CLI has been more widely used than Leiningen for a couple of years at this point and that trend is continuing.

Third, a lot of Clojure libraries are consumed as source, directly from GitHub or similar `git`-based repositories. Something the Clojure core team encourage and something that is directly supported by the Clojure CLI. You can see this in the `deps.edn` for this project:

```clojure
                      io.github.cognitect-labs/test-runner
                      {:git/tag "v0.5.1" :git/sha "dfb30dd"}
```

"packaging `<any Clojure library>` for Debian" doesn't make sense.
