### ISSUE TITLE
Set Default `builder-fn`/`table-fn`/`column-fn` per datasource

### ISSUE THREAD

**Issue by kirillsalykin** [seancorfield/next-jdbc#39]
It feels annoying to specify `:builder-fn` and other fns for every query or statement (insert statement returns inserted id for instance).

Maybe it makes sense to set it once per datasource?

Something like:
```
(defn as-kebab-maps ...)

(let [my-datasource (get-datasource {:builderfn as-kebab-maps :dbtype "..." :dbname "..." })]
    (with-open [connection (get-connection my-datasource)]
      (execute! connection [...])
      (reduce my-fn init-value (plan connection [...]))
      (execute! connection [...])
```

What do you think?

Thanks.

**Comment by seancorfield** [comment]
What you're asking for is not possible: when you call `get-connection`, you get a plain `java.sql.Connection` object back -- which has nowhere to hang any options.
