### ISSUE TITLE
Add support for JDBC `add/executeBatch`

### ISSUE THREAD

**Issue by holyjak** [seancorfield/next-jdbc#40]
## The problem

Inserting/update many rows (thousands or 10s of thousands, at least) can benefit considerably from using JDBC batching so that statements are sent in batches of a user-set size (e.g. 100) instead of making a round trip for each and every one. This article https://java-persistence-performance.blogspot.com/2013/05/batch-writing-and-dynamic-vs.html has some stats for a number of databases.

In particular I am speaking about [Statement.addBatch(sql)](https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#addBatch-java.lang.String- ) and the more efficient [PreparedStatement.addBatch()](https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html#addBatch--) + [Statement.execute[Large]Batch()](https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#executeBatch--)

*Note*: The goal is not to make this new function to run on any database, just to make it easy to use batching on databases that support it. (Including those that somewhat fake it and require extra connection params, though it is the user's responsibility to find that out and set those params, just as if they tried to use JDBC directly). I.e. just a tiny, friendly wrapper around JDBC.

### Caveats

Reportedly most databases nowadays support batching but not all and some - such as MySQL and PostgreSQL reportedly require extra configuration to actually do any batching, so that would need to be communicated clearly. JDBC drivers that do not support batching may choose to fake it (e.g. by sending the statements one by one) or, according to the `executeBatch` JavaDoc to throw an exception. So it is less portable and requires more care from the user. Still, it is a very valuable tool to have available, though it is "expert level" and should be only used when you understand JDBC batching and your DB. (The docstring could make that very clear.)

## Describe the solution you'd like

Built-in support for batch inserts/updates for at least prepared statements. Perhaps something like 

```clojure
(execute-batched!
  tx
  ["insert into tbl(id, char) values (?,?)" [[1 "a"], [2 "b"], [3 "c"]...]
  {:batch-size 500}) ;; default to something reasonable, e.g. 100 ?
```

## Describe alternatives you've considered

DIY - create a prepared statement with `prepare` and repeatedly call its `.addBatch()` and `next.jdbc.prepare/set-parameters` and its `.executeBatch`. Something like this (not tested yet):

```clojure
(defn execute-multi! [conn [sql params-seq]]
  (with-open [ps (jdbc/prepare conn [sql])]
    (->> (partition 100 params-seq)
         (run! (fn [batch]
                 (run! (fn [params]
                         (next.jdbc.prepare/set-parameters ps params)
                         (.addBatch ps))
                       batch)
                 (.executeBatch ps))))))
```

**Comment by seancorfield** [comment]
Note that `next.jdbc.sql/insert-mult!` produces a single `INSERT` statement with all the placeholders and all the parameters unrolled so it doesn't suffer from the problem that `clojure.java.jdbc` has where you need the SQL rewriting done to make the batch execution work (despite the fact I added that to the docstring recently, thinking it was still needed).

It does, however, potentially suffer from a different problem which is that you could produce a huge SQL statement if there are enough rows being inserted and that might be rejected by the driver or DB and/or you may hit a limit on the number of parameters for a `PreparedStatement`.

`clojure.java.jdbc`'s parameter format for batching -- with `:multi? true` -- was:
```
(old-jdbc/execute! db-spec ["...sql string..." [1 "a"] [2 "b"] [3 "c"] ...])
```
i.e., without wrapping them all in a single sequence. Thoughts on which is better/less confusing?

**Comment by seancorfield** [comment]
FYI, I tested that this works on MySQL as expected:
```
  (with-open [con (jdbc/get-connection ds {:rewriteBatchedStatement true})
              ps (jdbc/prepare con ["insert into status (id,name) values (?,?)"])]
    (run! #(.addBatch (p/set-parameters ps %))
          [[10 "ten"] [20 "twenty"] [30 "thirty"]])
    (.executeBatch ps))
```
It returns an `int[]`. For PostgreSQL, the option would be `:reWriteBatchedInserts true`.

Given that this is already possible (and pretty easy) with the current API, I'm not sure how much value there would be to add a bunch of new machinery for this? I don't want to expand the `Executable` protocol to add `-execute-batch` and have to add (and test) implementations for `Connection`, `DataSource`, and `PreparedStatement` -- I don't really want to bake this into the primary API at all.

Perhaps a helper (in `next.jdbc.prepare`) for adding all the batches of parameters? Or perhaps for the whole add'n'execute operation, so it could pour the result into a Clojure vector?
```
(p/execute-batch ps [[10 "ten"] [20 "twenty"] [30 "thirty"]])
```
That still expands the overall API surface (but not the primary API) so I'd still have to add tests for this.

I could certainly add this as an example in the "Prepared Statements" documentation page (and take no further action).

**Comment by seancorfield** [comment]
I've added https://github.com/seancorfield/next-jdbc/blob/master/doc/prepared-statements.md#batched-parameters to show how to execute batched parameters (as in the comment above), along with several caveats about how DB-specific it can be.

**Comment by holyjak** [comment]
(1) Yes, `insert-multi!` is a good alternative unless there is too many rows (due to length limits as you write) or you need an `update` instead. Regarding <q>where you need the SQL rewriting done</q> I believe this only applies to some DBs (MySQL, PostgreSQL), i.e. it is not a general problem. (Though it is pretty relevant to making batching work across all popular DBs; which I would leave up to the user, with proper warnings and such.)

(2) Passing the values as multiple arguments (old-jdbc) or a single sequence of sequences (above) - I proposed `[[], [], ..]` because it seemed to fit best with how `execute[-one]!` work now, taking `connectable sql-params opts`. Just `execute-batched!` naturally needs a "seq of seqs" instead just a sequence for its `sql-params`. But if you feel it is confusing do whatever seems better.

(3) Primary API x helper x docs only: You know the API best and can best asses where/if it fits in. From the point of view of a user, having an `execute-batch[ed]!` feels more natural, in line with `execute!` and `execute-one!` but I very much understand the desire to keep the API minimal, and I haven't realized that it is considerably more work than adding a function due to the protocols involved. So perhaps adding the add+execute helper `p/execute-batch` you proposed above would be a good compromise. (It would also need to take an optional `{:batch-size n}` with a reasonable default or communicate clearly that it is up to the user to call `partition` on her data and to call it `execute-batch` to control the batch size. "Docs only" is also possible but I think it would be really nice to have a built-in support.

**Comment by seancorfield** [comment]
(1) -- the new docs only mention rewriting in the context of PostgreSQL and MySQL (and give the specific options): I can't be more specific because I don't know how other databases handle this. A brief search suggests PostgreSQL handles bulk updates with `UPDATE .. FROM ..` which is a SQL extension?

(2) -- if batch execution is not part of the primary API then I'm fine with it taking the most appropriate format (which would indeed seem to be a vector of vectors).

(3) -- that's a good point about the batch size: it would have to have a reasonable default behavior -- perhaps treating it all as one batch, if `:batch-size` is omitted?

**Comment by holyjak** [comment]
(1) -- Ok! I haven't got that that comment referred to the docs. 

(2) -- Ok!

(3) -- I am not really sure what is a reasonable size. Would e.g. batch of 30 000 work on most DBs? Or 1000? From https://stackoverflow.com/questions/20883964/what-is-the-max-jdbc-batch-size "There's a diminishing return with increasing batch size, because the total time taken in network waits falls off quickly, so it's often not work stressing about trying to make batches as big as possible."

**Comment by seancorfield** [comment]
I love all the caveats about PG in that answer (9.4 was released four years ago so several of the caveats no longer apply -- but it does somewhat underscore my deliberate vagueness about what you can and cannot expect from a JDBC driver when trying to use batch execution!).

Anyway, I think my preference for `:batch-size` would be that if you omit it, `execute-batch!` should assume it can send the entire data set in one (batched) command and it's up to the user to supply a relevant size if the default won't work.

BTW, `partition` will silently drop items on the floor if the sequence doesn't have an exact multiple of `n` items (so if I implement this it will use `partition-all`).

**Comment by holyjak** [comment]
Thank you!

And thanks for the reminder of participation-all, you saved me some future
troubleshooting! ♥️

**Comment by seancorfield** [comment]
I'll probably cut 1.0.2 with this tomorrow.
