### ISSUE TITLE
Utilize protocol to get defaults (set-builder-fn, table-fn, label-fn and etc)

### ISSUE THREAD

**Issue by kirillsalykin** [seancorfield/next-jdbc#49]
**Is your feature request related to a problem? Please describe.**
It is pretty annoying to pass custom set-builder/table-fn/label-fn to every query or statement.

**Describe the solution you'd like**
It would help a lot if there would be a way to specify it only once. 
But having the possibility to pass override via `opts` still important.

**Describe the solution you'd like**
Maybe having a protocol to get defaults would help with this?
And if one wants to override defaults - it can be achieved with `extend-protocol`.

Similar to `ReadableColumn` approach.

**Comment by seancorfield** [comment]
Given that protocols are based on _types_ I don't see how this would work -- could you elaborate on what you have in mind?

**Comment by kirillsalykin** [comment]
Sorry for not being clear.

I propose to create a new protocol:
```
(defprotocol NamingConvention
  (builder-fn [this])
  ...)
```

Then `extend-protocol` to all types which extended by `Executable` (https://github.com/seancorfield/next-jdbc/blob/6bc716415f9cf853720528c06f5bdad3367686fc/src/next/jdbc/result_set.clj#L407):
- `java.sql.Connection`
- `javax.sql.DataSource`
- `java.sql.PreparedStatement`

And get default `builder-fn` using protocol 
(https://github.com/seancorfield/next-jdbc/blob/6bc716415f9cf853720528c06f5bdad3367686fc/src/next/jdbc/result_set.clj#L424)
`builder-fn (get opts :builder-fn (p/builder-fn this)`

If one wants to override it - he should `extend-protocol` to the java(x).sql types.

A bit annoying, but doable.

What do you think?

**Comment by kirillsalykin** [comment]
Hm, not sure it works...

**Comment by seancorfield** [comment]
Nope, because there are paths to `:builder-fn` that have nothing to dispatch on via a protocol.

**Comment by seancorfield** [comment]
I think you could base it on `ResultSet` -- I think everywhere that "gets" the `:builder-fn` option has access to a `rs` object...?

**Comment by kirillsalykin** [comment]
I'll play more with to ensure it actually works.
Will get back to you.

Thanks!

**Comment by seancorfield** [comment]
So you're thinking that the library would provide a default implementation for `Object` and then users could override it for `ResultSet` with their defaults instead?

I still feel this is really hacky...

**Comment by kirillsalykin** [comment]
I agree, feels hacky, but cant think of any other approach to override default behavior w/o global variable.

**Comment by seancorfield** [comment]
I canvassed some of Clojure contributors and everyone who had an opinion felt this was a bad approach. Protocols should really only be extended either by the code that owns the protocol (`next.jdbc` in this case) or owns the type -- and the connection to `ResultSet` was felt to be tenuous at best.

So I'm closing this out. My original suggestion of creating a wrapper API still stands -- but I think that should be in user code.

**Comment by kirillsalykin** [comment]
I agree.

Thanks for investigating it.
