### ISSUE TITLE
Improve docs for prepare/SettableParameter, result-set/ReadableColumn protocols

### ISSUE THREAD

**Issue by holyjak** [seancorfield/next-jdbc#54]
It is not clear that to add support for custom data types (e.g. `java.time.Instant`), the correct way is to extend the protocols `prepare/SettableParameter` and `result-set/ReadableColumn`.

It would therefore be helpful if their docstring linked to each other and if the Guide contained a section on this topic.

Thank you!!!

**Comment by seancorfield** [comment]
Those protocols are documented in the Prepared Statements and Result Set Builders sections of the docs, with examples, but I'll try to make that easier to find. It'll be a week or so before I have time to make those doc updates, just FYI.

**Comment by seancorfield** [comment]
GIven that https://github.com/seancorfield/next-jdbc/blob/master/doc/result-set-builders.md#readablecolumn and https://github.com/seancorfield/next-jdbc/blob/master/doc/prepared-statements.md#prepared-statement-parameters both exist and give examples of how to extend reading from and writing to the database with additional types, are there specific clarifications you think need to be added to those sections?

The former (reading values) ends with this note pointing to `SettableParameter` in the next section of the docs: "Note that the converse, converting Clojure values to database-specific types is handled by the `SettableParameters`, discussed in the next section (Prepared Statements)."

I'll correct that to say "`next.jdbc.prepare/SettableParameter` protocol". I'll add a similar note in the latter section, pointing back to `next.jdbc.result-set/ReadableColumn` for reading values.

I'll add a new section in Getting Started, above https://github.com/seancorfield/next-jdbc/blob/master/doc/getting-started.md#support-from-specs that says to read those two sections if you need to read or write additional data types not handled natively in the JDBC driver you are using. 

Anything else that you think needs changing?

**Comment by holyjak** [comment]
I think a brief section in the Guide is all that's needed. Thank you!
