### ISSUE TITLE
Documentation or helpers for `get-by-ids` like queries

### ISSUE THREAD

**Issue by dgtized** [seancorfield/next-jdbc#56]
It's not clear from documentation what the recommended approach is for handling `select * from table where id in (...)` type queries. More generally, this is to address cases where there are a variable number of bind params in a prepared statement. The best approach I have found is to use something like:

```clojure
(defn get-by-ids [connectable table ids]
  (let [params (str/join "," (repeat (count ids) "?"))
        sql (str "select * from " table " where id in (" params ")")]
    (sql/query connectable (cons sql ids))))
```

I see that `next.jdbc.sql/as-?` is private and handles a portion of this functionality but for `for-insert` and `for-insert-multi`. It would be nice if there was a recommended lookup function ala `get-by-id` or even allow `find-by-keys` to look for all primary keys in a sequence. Either as a direct helper function, or just a recommended approach in the documentation.

I also did some reading on how jdbc itself handles this issue, and I see it's not entirely compatible with [PreparedStatement#setArray](https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html#setArray-int-java.sql.Array-), as that's more for `id = ANY(?)` cases, which is only compatible with some sql databases. There are several examples of building up a long list of `?` bind params in prepared statement. I'm aware that generating a really long list of individual bind params is not very performant. However, I think it's a pretty useful for smaller lists, so it would be nice if there was a documented or suggested approach for fetching a batch of rows.

I'm also aware that `next.jdbc` is aiming for lower level access and that something like `honeysql` may be a better place for this type of query generation. Even if that is the case, I think it would be helpful if there was a recommended solution in `next.jdbc`'s documentation, even if it blesses a solution in another library.

Thanks for providing this excellent library!

**Comment by seancorfield** [comment]
I recommend using `honeysql` for this. I have no intention of expanding `next.jdbc.sql` to include any extra functions ("slippery slope", don't want to encourage future additions, don't want to become a DSL, etc).
