### ISSUE TITLE
sql/insert-multi! doesn't work with Oracle

### ISSUE THREAD

**Issue by holyjak** [seancorfield/next-jdbc#57]
**Describe the bug**
`sql/insert-multi!` fails on Oracle when there are multiple rows.

The input produced by `sql/for-insert-multi` works for single row:

```clojure
(execute! (user/bean "dataSource") ["INSERT INTO run_limit (id, profile_id, profile_category, limit_value) VALUES (?, ?, ?, ?)" 2816 "e684e309-a68f-4458-86a7-95d98eec3a99" "SERVICES" 0M])
; => OK
```

but fails for multiple rows:

```clojure
(execute! (user/bean "dataSource") ["INSERT INTO run_limit (id, profile_id, profile_category, limit_value) VALUES (?, ?, ?, ?), (?, ?, ?, ?)" 2816 "e684e309-a68f-4458-86a7-95d98eec3a99" "SERVICES" 0M 2816 "e684e309-a68f-4458-86a7-95d98eec3a99" "DATA" 0M])
; =>
; Execution error (SQLException) at oracle.jdbc.driver.DatabaseError/throwSqlException (DatabaseError.java:113).
; ORA-00933: SQL command not properly ended
```

The [correct syntax Oracle solution is to use `INSERT ALL`](https://www.oracletutorial.com/oracle-basics/oracle-insert-all/) (can't the DB vendors finally agree on this stuff?!):

```sql
INSERT ALL
  INTO run_limit(id, profile_id, profile_category, limit_value) VALUES(?,?,?)
  INTO run_limit(id, profile_id, profile_category, limit_value) VALUES(?,?,?)
```

I am not sure whether it is in the scope of next.jdbc to support every possible weird database so perhaps just close this as "won't fix until Oracle gets its sh*#! together" :-)

**Expected behavior**
`sql/insert-multi!` should work for Oracle just as it does for H2 etc.

**Stacktraces**

[oracle.jdbc.driver.OraclePreparedStatement execute "OraclePreparedStatement.java" 3521]
[com.mchange.v2.c3p0.impl.NewProxyPreparedStatement execute "NewProxyPreparedStatement.java" 989]
[next.jdbc.result_set$stmt__GT_result_set invokeStatic "result_set.clj" 416]
[next.jdbc.result_set$stmt__GT_result_set invoke "result_set.clj" 411]
[next.jdbc.result_set$fn__16830 invokeStatic "result_set.clj" 503]
[next.jdbc.result_set$fn__16830 invoke "result_set.clj" 443]
[next.jdbc.protocols$fn__16340$G__16305__16349 invoke "protocols.clj" 33]
[next.jdbc$execute_BANG_ invokeStatic "jdbc.clj" 177]
[next.jdbc$execute_BANG_ invoke "jdbc.clj" 167]

**project.clj/deps.edn**

```
compile 'org.clojure:clojure:1.10.1'
compile 'seancorfield:next.jdbc:1.0.5'
```

**Environment (please complete the following information):**
 - OS: OSX
 - Clojure Version: 1.10.1
 - Database: Oracle Standard Edition One 11.2.0.4.v19
 - Driver Library Version: com.oracle/ojdbc14 "10.2.0.5.0"

**Comment by seancorfield** [comment]
Yay Oracle! 👎 

This is definitely not within `next.jdbc`'s scope for the SQL helper functions. I'd suggest writing a SQL helper for it yourself and using `execute-one!` (optionally with `:return-keys true`?).

Reading up on it indicates that `INSERT ALL` can't insert more than a 1,000 rows at a time -- and the same is true for MS SQL Server (with the expected `INSERT` syntax with multiple `VALUES` `(..)` expressions) -- something I did not know until now.

Note: `INSERT ALL` is not supported by HoneySQL either.

**Comment by holyjak** [comment]
Perhaps it would be worth mentioning in the docstring of the fn, that it doesn't work with Oracle? (Which is, sadly, still widely used...)

**Comment by seancorfield** [comment]
Good point. Will do. There are quite a lot of caveats with `insert- multi!` 😕

**Comment by seancorfield** [comment]
Docs updated.
