### ISSUE TITLE
Add `upsert` friendly sql function

### ISSUE THREAD

**Issue by kirillsalykin** [seancorfield/next-jdbc#59]
I would help to have the `upsert!` function, which first attempts to update and if it fails - inserts the record.

```
(defn upsert! [db table row where-clause]
  (jdbc/with-db-transaction [tx db]
    (let [result (jdbc/update! tx table row where-clause {:return-keys true})]
      (if (nil? result)
        (first (jdbc/insert! tx table row))
        result))))
```

**Comment by seancorfield** [comment]
The "friendly" SQL functions in `next.jdbc.sql` are not part of the "core API" and exist purely to make the transition from `clojure.java.jdbc` a bit easier -- therefore this is out of scope (and the code seems to be using `clojure.java.jdbc`, not `next.jdbc`?).
