### ISSUE TITLE
Oracle does not honor .getTableName apparently

### ISSUE THREAD

**Issue by seancorfield** [seancorfield/next-jdbc#63]
**Describe the bug**
When using Oracle, you do not get qualified column names. `.getTableName` returns an empty string. This also means that you can't use `:qualifier-fn (constantly "table")` to supply a qualifier because the `:qualifier-fn` is not actually called when the table name is unknown.

Update the docs around qualified column names to reflect that not all databases support it (e.g., Oracle).

Update the migration docs around `:qualifier` to use `:label-fn #(str "qualifier/" %)` and recommend `as-modified-unqualified-maps`.

**Comment by holyjak** [comment]
This explains why my tests worked with Derby but failed with Oracle :-) Thank you! (To you - not to ORacle ;-))
