### ISSUE TITLE
as-unqualified-maps doesn't unqualify :next.jdbc/update-count

### ISSUE THREAD

**Issue by aiba** [seancorfield/next-jdbc#68]
Not sure if this is a bug or by design, but I was surprised to see that when calling:

```clojure
(next.jdbc/execute! conn
                    ["UPDATE ..."]
                    {:builder-fn next.jdbc.result-set/as-unqualified-maps})
```

The result looks like: `[#:next.jdbc{:update-count 1}]`.

Should `as-unqualified-maps` unqualify all result keywords, or is the :next.jdbc/update-count special in some way?

**project.clj/deps.edn**

```
org.clojure/clojure       {:mvn/version "1.10.1"}
seancorfield/next.jdbc    {:mvn/version "1.0.8"}
org.postgresql/postgresql {:mvn/version "42.2.8"}
```

**Environment (please complete the following information):**

`macos, JDK13, PostgreSQL 10.7`

**Comment by seancorfield** [comment]
It's by design -- you get that back when there is no `ResultSet` object available (so the `:builder-fn` is not run). I'll update the docs to make that clearer for the next release.
