### ISSUE TITLE
Document how to use CLOB and BLOB fields in queries

### ISSUE THREAD

**Issue by jsyrjala** [seancorfield/next-jdbc#70]
Currently documentation doesn't describe how to handle CLOB and BLOB fields in queries. You have to open a reader/input stream from the Clob/Blob object and read it while the query is running. Reading the fields after the query is finished does not work because e.g getCharacterStream()  throws. For example with H2:

```
Exception: org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-200]
```

This kind of pattern seems to work. 
```
(defn read-clob [^Clob clob]
  (with-open [reader (jio/reader (.getCharacterStream clob))]
    (slurp reader)))

(defn- column-reader
  [^ResultSet rs ^ResultSetMetaData _ ^Integer i]
  (let [obj (.getObject rs i)]
    (cond (instance? Clob obj) (read-clob obj)
          :default obj)))

;; create builder-fn that can be passed to e.g jdbc/execute command
{:builder-fn (opt/as-maps-adapter
   opt/as-unqualified-lower-maps
   column-reader)}
```

Maybe next-jdbc could also contain some helper functions  to handle CLOB/BLOB fields? For example a column-reader function that reads the contents of CLOB/BLOB fields.

**Comment by seancorfield** [comment]
Good suggestion!

Added:
* `next.jdbc.result-set/clob->string` -- given a CLOB value, return a string
* `next.jdbc.result-set/clob-column-reader` -- example column reader that expands CLOB column values

Documentation updated to describe it in the Result Set Builders section.

**Comment by jsyrjala** [comment]
Thanks. One thing to consider is whether to add also similar support for [java.sql.Blob](https://docs.oracle.com/javase/7/docs/api/java/sql/Blob.html) add the same time? Basically Blob is same thing as Clob but for binary data. Maybe make a combined column-reader for both or a `blob-column-reader`.

**Comment by seancorfield** [comment]
I don't think there's a single generic way to handle BLOB columns -- the interpretation of that binary data is entirely up to the application. Accordingly, I'd rather leave the processing of binary data up to users -- they have the `clob` helper/example as a starting point for doing something similar for blobs.

**Comment by jsyrjala** [comment]
I was thinking about converting the Blob to `byte[]`. But anyway the main thing is to have some pointer in docs.

**Comment by seancorfield** [comment]
Given the new docs for the clob-related examples, I think that's enough of a hint.

**Comment by seancorfield** [comment]
If you want to submit a PR to expand that part of the documentation to provide more of a hint for blob, feel free. I'm just not going to write it myself.

**Comment by seancorfield** [comment]
I added more documentation after all :)

**Comment by jsyrjala** [comment]
Thanks a lot!
