### ISSUE TITLE
with-transaction linter problem

### ISSUE THREAD

**Issue by valerauko** [seancorfield/next-jdbc#74]
**Describe the bug**
The final `(or ~opts {})` in the `with-transaction` macro expands to `(or nil {})` which linters (eastwood) yell about as being constantly true.

**To Reproduce**
Write a `with-transaction` without options and lint the file

**Expected behavior**
No constant `or`

**Additional context**
If such a fix is acceptable, I can put up a PR to move the unqoute before the `or`

**Comment by seancorfield** [comment]
There were several Eastwood warnings so I addressed all of them. Thanks for the nudge!
