### ISSUE TITLE
Default schema problem with get-connection

### ISSUE THREAD

**Issue by nikolavojicic** [seancorfield/next-jdbc#78]
**Describe the bug**

`next.jdbc/get-connection` consults [HikariCP](https://github.com/brettwooldridge/HikariCP) `:schema` property (used to set the default schema name) only the first time it is invoked. Subsequent invocations throw `"relation "table" does not exist"` if schema name is not passed along with the table name.

`next.jdbc/with-transaction` doesn't have this problem if it is not used after `next.jdbc/get-connection` is invoked. Also, when used before, it "fixes" `next.jdbc/get-connection`'s behaviour for that pool.

**To Reproduce**
```clojure
(require '[next.jdbc])
(require '[next.jdbc.sql])

(defn make-pool []
  (next.jdbc.connection/->pool
   com.zaxxer.hikari.HikariDataSource
   {:poolName "pool"
    :dbtype "postgresql"
    :host "localhost"
    :port 5432
    :dbname "dbname"
    :username "username"
    :password "password"
    :schema "schema"
    :autoCommit false
    :maximumPoolSize 2
    :connectionTimeout 30000}))

(defn via-get-connection [pool]
  (with-open [con (next.jdbc/get-connection pool)]
    (next.jdbc.sql/query
     con ["SELECT * FROM table"])))

(defn via-with-transaction [pool]
  (next.jdbc/with-transaction [con pool]
    (next.jdbc.sql/query
     con ["SELECT * FROM table"])))

(def pool (make-pool))

(via-get-connection pool) ;; => []

(via-get-connection pool)
;; => Execution error (PSQLException) at org.postgresql.core.v3.QueryExecutorImpl/receiveErrorResponse (QueryExecutorImpl.java:2497).
;;    ERROR: relation "table" does not exist

(via-with-transaction pool)
;; => Execution error (PSQLException) at org.postgresql.core.v3.QueryExecutorImpl/receiveErrorResponse (QueryExecutorImpl.java:2497).
;;    ERROR: relation "table" does not exist

(def pool (make-pool))

(via-with-transaction pool) ;; => []
(via-with-transaction pool) ;; => []
(via-get-connection   pool) ;; => []
(via-get-connection   pool) ;; => []

```

**Environment:**

 - OS: Windows 7
 - Java Version: AdoptOpenJDK jdk-11.0.3.7-openj9
 - Clojure Version: 1.10.1
 - Database: PostgreSQL 10
 - Driver Library Version: org.postgresql/postgresql "42.2.8"
 - Next-jdbc Version: seancorfield/next.jdbc "1.0.10"

**Comment by seancorfield** [comment]
Thank you for the detailed repro case! Wow, what a weird bug. Will take a look in a few days, when I've caught up with work, after being away this week at Clojure/conj.

**Comment by seancorfield** [comment]
It sounds a bit like this issue to me: https://github.com/brettwooldridge/HikariCP/issues/1369 -- that shows that HikariCP's `schema` setting operation gets rolled back if you do not have a commit right at the beginning of the workload -- which would explain why running `with-transaction` "works" but `with-connection` does not.

Based on that issue's workaround, I think if you specify `:connectionInitSql "COMMIT;"` in the call to `->pool`, the problem with disappear.

If you can confirm that, I can add a note to the HikariCP section of the docs.

**Comment by nikolavojicic** [comment]
Yes, `:connectionInitSql "COMMIT;"` fixed the problem. Thanks!

**Comment by seancorfield** [comment]
Thank you for confirming that, I'll add (yet another) PostgreSQL-specific note here :)
