### ISSUE TITLE
When writing new SQL-level functions, the private builder stuff is useful

### ISSUE THREAD

**Issue by seancorfield** [seancorfield/next-jdbc#81]
@zcaudate wrote some (PostgreSQL-specific) upsert functions and used several of the private functions from `next.jdbc.sql`. Those should be made public in a new `next.jdbc.sql.builder` namespace for folks who want to leverage them.

That means documenting them properly and moving tests etc.

**Comment by zcaudate** [comment]
There where two things I added for Postgres:

- Appending FOR UPDATE to the end of a select statement for locking reads. I believe mysql also has this:
https://dev.mysql.com/doc/refman/5.7/en/innodb-locking-reads.html

   - It'll be great if there was a `:suffix` option to `sql/for-query`

- Adding `ON CONFLICT (id) UPDATE SET ...<VALUES>... ` for upsert. I think mysql also has this along with `ON DUPLICATE KEY` 

   - Not sure what can be done with this one.

**Comment by seancorfield** [comment]
All the `for-*` SQL builders support a `:suffix` option now, which will make the code for your upserts easier to write since you can reuse `for-insert`/`for-insert-multi` with the `ON CONFLICT ...` string passed in as the `:suffix`.
