### ISSUE TITLE
Allow to apply :qualifier-fn to empty table name

### ISSUE THREAD

**Issue by serioga** [seancorfield/next-jdbc#88]
**Is your feature request related to a problem? Please describe.**

I want to assign static namespace to all columns like
```clojure
{:qualifier-fn (constantly "db")}
```

But columns without table name don't have namespace in result.

**Describe the solution you'd like**

Remove `(not-empty)` before `((:qualifier-fn opts))` in places like https://github.com/seancorfield/next-jdbc/blob/c17a425df6176f7cd45d4fad5a8f146b2400ee4a/src/next/jdbc/result_set.clj#L50-L52

Then :qualifier-fn can handle empty input itself.

**Comment by seancorfield** [comment]
This would be a breaking change since it would produce keywords like `:/col` in situations where the table name was not available. I could move the `(not-empty)` call _after_ the qualifier call which probably wouldn't break anything. You can get what you want with `:label-fn #(str "db." %)` today.

**Comment by seancorfield** [comment]
FWIW, this is explicitly called out on the **Migration** page of the docs:

> If you used `:qualifier`, you may be able to get the same effect with `as-maps`, `as-lower-maps`, or `as-modified-maps`. Otherwise, you may need to specify the fixed qualifier via the `:label-fn #(str "my_qualifier/" %)`. You might think you could use `:qualifier-fn (constantly "my_qualifier")` for this but it is only called when the column has a known table name so it wouldn't be applied for derived values (and some databases don't provide the table name, so it wouldn't be applied at all for those databases).

**Comment by serioga** [comment]
>  You can get what you want with `:label-fn #(str "db/" %)` today.

As I understand in this case I will get keywords with _name_ "db/xxx" without namespace, and it will not be equal to `:db/xxx` literal.

**Comment by seancorfield** [comment]
```clojure
user=> (= :db/level (keyword "db/level"))
true
```

**Comment by serioga** [comment]
> 
> 
> ```clojure
> user=> (= :db/level (keyword "db/level"))
> true
> user=> (name (keyword "db/level"))
> "level"
> user=> (namespace (keyword "db/level"))
> "db"
> ```

but in your code it is executed like `(keyword (:qualifier-fn opts) "db/level")` with 2 arities, isn't it?

I remember I tried queries like `SELECT 1 AS "db/level"` and did not get namespaced keywords...

**Comment by seancorfield** [comment]
Ah, I'm following you now. You're right that it uses the 2-arity version and that's not actually correct if the table name is unavailable. It is a bug, but not the bug I thought it was.

**Comment by serioga** [comment]
> 
> 
> FWIW, this is explicitly called out on the **Migration** page of the docs:
> 
> > If you used `:qualifier`, you may be able to get the same effect with `as-maps`, `as-lower-maps`, or `as-modified-maps`. Otherwise, you may need to specify the fixed qualifier via the `:label-fn #(str "my_qualifier/" %)`. You might think you could use `:qualifier-fn (constantly "my_qualifier")` for this but it is only called when the column has a known table name so it wouldn't be applied for derived values (and some databases don't provide the table name, so it wouldn't be applied at all for those databases).

This is just not possible with available function set.
We cannot specify builder-fn without qualifier but with `:label-fn #(str "my_qualifier/" %)`.

**Comment by seancorfield** [comment]
You'd pass `:label-fn identity` in that case.

That section of the migration docs has been updated: the 1-arity `keyword` call is used when the table name is not available _and the `:qualifier-fn` returns an empty string_ so you _can_ use `:qualifier-fn (constantly "db")` now and the docs make it clear you must also pass `:label-fn` as well.

See the commit above that closed this issue.
