### ISSUE TITLE
Remove extra assert from `as-...` result set functions?

### ISSUE THREAD

**Issue by serioga** [seancorfield/next-jdbc#89]
I feel like these asserts are not needed because they check for options which are checked again in the underlying function. 

https://github.com/seancorfield/next-jdbc/blob/c17a425df6176f7cd45d4fad5a8f146b2400ee4a/src/next/jdbc/result_set.clj#L170-L180

Not everyone disable asserts in production :-)

**Comment by seancorfield** [comment]
Good idea! Done.
