### ISSUE TITLE
Result of next.jdbc.prepare/->factory is not reused

### ISSUE THREAD

**Issue by ikitommi** [seancorfield/next-jdbc#9]
Many public functions in `next.jdbc` call `rs/execute!`, which creates a `factory` object, which seems immutable but is only used once. Supporting reuse of the factory would yield better perf.

```clj
user=> (require '[next.jdbc.prepare :as p])
nil
user=> (p/->factory {})
#object[next.jdbc.prepare$__GT_factory$fn__1031 0x58606c91 "next.jdbc.prepare$__GT_factory$fn__1031@58606c91"]
user=> (cc/quick-bench (p/->factory {}))
Evaluation count : 11818956 in 6 samples of 1969826 calls.
             Execution time mean : 44,151731 ns
    Execution time std-deviation : 2,325906 ns
   Execution time lower quantile : 42,078360 ns ( 2,5%)
   Execution time upper quantile : 47,134326 ns (97,5%)
                   Overhead used : 8,509989 ns
nil
```

**Comment by seancorfield** [comment]
Good catch. This is an artifact of earlier code that _did_ reuse the factory and was much faster for being able to preprocess the options just once, and then invoking the `PreparedStatement` creation multiple times.
