### ISSUE TITLE
new dbtype with classname doesn't seem to work

### ISSUE THREAD

**Issue by danielsz** [seancorfield/next-jdbc#90]
**Describe the bug**
Can't create datasource for new dbtype, despite using className as instructed.

**To Reproduce**
```
(jdbc/get-connection {:dbtype "mariadb" :className "org.mariadb.jdbc.Driver" :dbname "db" :host "127.0.0.1" :port 3306 :user "user" :password "password"})
```
**Result**
```
Execution error (ExceptionInfo) at next.jdbc.connection/spec->url+etc (connection.clj:201).
Unknown dbtype: mariadb
```
**Expected behavior**
From the docs: If you want to use a database that is not in this list, you can specify a new :dbtype along with the class name of the JDBC driver in :classname. You will also need to specify :port. 

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: openjdk 11.0.6 2020-01-14
 - Clojure Version: 1.10.1
 - Database: Mariadb
 - Driver Library Version: MariaDB Connector/J 2.5.4

**Comment by seancorfield** [comment]
It should be `:classname` not `:className`.

**Comment by seancorfield** [comment]
I'm changing the exception to `Unknown dbtype: <dbtype>, and :classname not provided`  to make this sort of error clearer.

**Comment by danielsz** [comment]
Awesome. Thanks.
