### ISSUE TITLE
Move extraction of :qualifier-fn/:label-fn out of the loop

### ISSUE THREAD

**Issue by serioga** [seancorfield/next-jdbc#91]
I suggest to do `(:qualifier-fn opts)` and `(:label-fn opts)` before `mapv` for better performance.

https://github.com/seancorfield/next-jdbc/blob/c17a425df6176f7cd45d4fad5a8f146b2400ee4a/src/next/jdbc/result_set.clj#L50-L54

Also I would combine extraction and asserts to avoid double extraction when asserts are enabled.

**Comment by seancorfield** [comment]
Good suggestion -- done here and elsewhere in `result_set.clj`.

**Comment by serioga** [comment]
> 
> 
> Good suggestion -- done here and elsewhere in `result_set.clj`.

Looks like something should be touched in https://github.com/seancorfield/next-jdbc/blob/master/src/next/jdbc/optional.clj as well.

**Comment by seancorfield** [comment]
Thanks for the reminder, yes, that duplicates some of `result_set.clj` -- removed the unnecessary `assert` calls there too.
