### ISSUE TITLE
Suggestion: mention important fact about transactions from getting-started in documentation

### ISSUE THREAD

**Issue by serioga** [seancorfield/next-jdbc#92]
https://github.com/seancorfield/next-jdbc/blob/master/doc/getting-started.md#user-content-datasources-connections--transactions

> If with-transaction is given a datasource, it will create and close the connection for you. If you pass in an existing connection, with-transaction will set up a transaction on that connection and, after either committing or rolling back the transaction, will restore the state of the connection and leave it open

I suggest to mention this important fact in the “working with transactions” documentation
https://github.com/seancorfield/next-jdbc/blob/master/doc/transactions.md

**Comment by seancorfield** [comment]
Repeated that fact in the transaction page.
