### ISSUE TITLE
Give the ResultSet as a parameter to next.jdbc.result-set/ReadableColumn functions

### ISSUE THREAD

**Issue by luontola** [seancorfield/next-jdbc#97]
**Is your feature request related to a problem? Please describe.**
I'm trying to make next.jdbc read [Snowflake's TIMESTAMP_TZ](https://docs.snowflake.net/manuals/sql-reference/data-types-datetime.html#timestamp-ltz-timestamp-ntz-timestamp-tz) as `java.time.OffsetDateTime` instances. The TIMESTAMP_TZ type includes timezone offset information (unlike e.g. PostgreSQL's TIMESTAMPTZ), but the Snowflake JDBC driver reads it as `java.sql.Timestamp` which doesn't include timezone information. My `ReadableColumn` usage looks like this:

```clj
(extend-protocol result-set/ReadableColumn
  java.sql.Timestamp
  (read-column-by-label ^Instant [^java.sql.Timestamp val _label]
    (.toInstant val))
  (read-column-by-index ^Instant [^java.sql.Timestamp val ^ResultSetMetaData rsmeta idx]
    (case (.getColumnTypeName rsmeta idx)
      "TIMESTAMPTZ" (.toInstant val) ;; TODO: cannot read the offset, because no access to ResultSet
      "TIMESTAMPLTZ" (.toInstant val)
      "TIMESTAMPNTZ" (.toLocalDateTime val)))
```

**Describe the solution you'd like**
I'd like the `ReadableColumn` functions to also receive the `ResultSet` instance as a parameter. This would help to avoid writing a column reader (see below).

**Describe alternatives you've considered**
My workaround is to write a column reader, but it has the downside of making `execute!` et al. calls more complex, unless also creating wrapper functions for them.

My column reader:
```clj
(def ^:private ^DateTimeFormatter timestamp-tz3
  (DateTimeFormatter/ofPattern "yyyy-MM-dd HH:mm:ss.SSS Z"))

(defn fix-timestamp-tz [^java.sql.Timestamp val ^ResultSet rs ^ResultSetMetaData rsmeta ^Integer idx]
  (if (= "TIMESTAMPTZ" (.getColumnTypeName rsmeta idx))
    (-> (OffsetDateTime/parse (.getString rs idx) timestamp-tz3)
        ;; XXX: the default TIMESTAMP_TZ_OUTPUT_FORMAT shows only 3 fractions, so the string representation doesn't have full precision
        (.withNano (.getNano (.toInstant val))))
    val))

(defn column-reader [^ResultSet rs ^ResultSetMetaData rsmeta ^Integer idx]
  (when-let [val (.getObject rs idx)]
    (cond-> val
      (instance? java.sql.Timestamp val) (fix-timestamp-tz rs rsmeta idx))))
```

P.S. If the database driver would be JDBC 4.2 compatible (Snowflake isn't yet), the above `fix-timestamp-tz` could be replaced with a simple `(.getObject rs idx OffsetDateTime)`, but that still requires access to the `ResultSet` because the default type is `java.sql.Timestamp`.

**Comment by seancorfield** [comment]
Changing `ReadableColumn` like that would break the existing code that is using it so, no, that can't happen.

The column reader approach is designed for cases like this (minority, outlying driver peculiarities).

I'm still considering ways to provide "default options" without impacting performance but, for now, you'll need to pass `:builder-fn` as an option with an `as-maps-adapter`.

**Comment by seancorfield** [comment]
In our code at work, we don't bother with wrappers. We tend to just `def` a private `jdbc-opts` Var at the top of a namespace that uses `next.jdbc` and just provide that as the last argument to each call. It's not worth writing a wrapper for that.

**Comment by luontola** [comment]
Thanks. I’ll try that. 👌
